/**
 * save-generation.ts
 *
 * Downloads kie.ai result URLs and saves them to Cloudflare R2.
 * Returns R2 public URLs on success, falls back to the original URL on failure.
 *
 * Storage path layout in R2:
 *   users/{userId}/images/{timestamp}-{index}.{ext}
 *   users/{userId}/videos/{timestamp}-{index}.{ext}
 */

import { getStorageService } from '@/shared/services/storage';

function extFromUrl(url: string, mediaType: 'image' | 'video'): string {
  try {
    const match = new URL(url).pathname.match(/\.(\w{2,4})$/);
    if (match) return match[1].toLowerCase();
  } catch {}
  return mediaType === 'video' ? 'mp4' : 'jpg';
}

/**
 * Extract the storage key from a public URL.
 * All files generated by saveResultsToR2 are stored under users/…, so we
 * can reliably extract the key by matching that path segment.
 */
function keyFromUrl(url: string): string | null {
  try {
    const { pathname } = new URL(url);
    const match = pathname.match(/\/?users\/[^?#]+/);
    return match ? match[0].replace(/^\//, '') : null;
  } catch {
    return null;
  }
}

/**
 * Deletes files from storage by their public URLs (best-effort).
 * Only deletes files that were uploaded by saveResultsToR2 (i.e., URLs
 * containing the users/ path prefix).  Falls back silently on any error.
 */
export async function deleteFilesFromStorage(urls: string[]): Promise<void> {
  if (!urls.length) return;
  let storage: Awaited<ReturnType<typeof getStorageService>>;
  try {
    storage = await getStorageService();
  } catch {
    return;
  }
  await Promise.all(
    urls.map(async (url) => {
      try {
        const key = keyFromUrl(url);
        if (key) await storage.deleteFile(key);
      } catch {
        // ignore
      }
    })
  );
}

export async function saveResultsToR2({
  userId,
  mediaType,
  kieUrls,
}: {
  userId:    string;
  mediaType: 'image' | 'video';
  kieUrls:   string[];
}): Promise<string[]> {
  if (!kieUrls.length) return [];

  let storage: Awaited<ReturnType<typeof getStorageService>>;
  try {
    storage = await getStorageService();
  } catch {
    // Storage not configured — return original URLs
    return kieUrls;
  }

  const folder = mediaType === 'video' ? 'videos' : 'images';
  const ts     = Date.now();

  const saved = await Promise.all(
    kieUrls.map(async (url, i) => {
      try {
        const ext    = extFromUrl(url, mediaType);
        const key    = `users/${userId}/${folder}/${ts}-${i}.${ext}`;
        const result = await storage.downloadAndUpload({
          url,
          key,
          contentType: mediaType === 'video' ? 'video/mp4' : 'image/jpeg',
          disposition: 'inline',
        });
        return result.success && result.url ? result.url : url;
      } catch {
        return url; // Fall back to kie.ai URL so the user still sees a result
      }
    })
  );

  return saved;
}
